#!/bin/bash

sprite4 idx 
        sprite4_strelka2_install/share/demo/strelka/data/NA12891_demo20.fq

sprite4 map -s 1 \
        sprite4_strelka2_install/share/demo/strelka/data/demo20.fa \
        sprite4_strelka2_install/share/demo/strelka/data/NA12891_demo20.fq

sprite4 sampa -s 1 \
        sprite4_strelka2_install/share/demo/strelka/data/demo20.fa

sprite4 varcall -s 1 \
        sprite4_strelka2_install/share/demo/strelka/data/demo20.fa
